server:
  port: 88
spring:
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
    request-context-attribute: request
  datasource:
    src:
      jdbc-url: jdbc:mysql://192.168.33.112:3306/pms?useSSL=false
      url: ${spring.datasource.src.jdbc-url}
      username: root
      password: abc123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      mapperLocation: classpath*:com.kingrein.okitmigration.mapperSrc/*.xml
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 600000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    dest:
      jdbc-url: jdbc:mysql://127.0.0.1:3318/pms_dest?useSSL=false
      url: ${spring.datasource.dest.jdbc-url}
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      mapperLocation: classpath*:com.kingrein.okitmigration.mapperDest/*.xml
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 600000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  record:
    rootDir: D:/temp
    projectListFile: projectlist.txt
    projectMapFile: projectmap.txt
    unitMapFile: unitmap.txt
    userMapFile: usermap.txt
    entityFile: entityselected.txt
    svnFile: svnnode.txt
    ticketMapFile: ticketmap.txt
    requirementMapFile: requirementmap.txt
    taskMapFile: taskmap.txt
    testcaseMapFile: testcasemap.txt
    memoryMapFile: memorymap.txt
    forumMapFile: forummap.txt
    riskMapFile: riskmap.txt
    questionMapFile: questionmap.txt
    workflowMapFile: workflowmap.txt
logging:
  level:
    com.kingrein.okitmigration: debug
  path: D:/temp
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %class{36} %L %M - %msg%xEx%n"
  file:
    max-size: 10MB