server:
  port: 8080
spring:
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
    request-context-attribute: request
  datasource:
    src:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/pms_src?useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      mapperLocation: classpath*:com.kingrein.okitmigration.mapperSrc/*.xml
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    dest:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/pms?useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      mapperLocation: classpath*:com.kingrein.okitmigration.mapperDest/*.xml
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  record:
    rootDir: D:/temp
    projectListFile: projectlist.txt
    projectMapFile: projectmap.txt
    unitMapFile: unitmap.txt
    userMapFile: usermap.txt
    ticketMapFile: ticketmap.txt
    requirementMapFile: requirementmap.txt
    taskMapFile: taskmap.txt
    testcaseMapFile: testcasemap.txt
    memoryMapFile: memorymap.txt
logging:
  level:
    com.kingrein.okitmigration: debug